version: '3.2'

services:
  soup:
    container_name: soup
    image: "ghcr.io/nicolasboulard/soup:master"
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=soup.settings.prod
    ports:
      - 8000:8000
    volumes:
      - ./docker/docker-compose/db/:/app/db/
      - ./docker/docker-compose/conf/prod.py:/app/soup/settings/prod.py
    networks:
      - souptor

networks:
  souptor:
    external: true
#    networks:
#      - db
#
#networks:
#  db:
#    internal:
#      name: db