# Generated by Django 4.1.1 on 2022-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soupui", "0003_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
