# Generated by Django 4.1.1 on 2022-11-07 13:14

from django.db import migrations, models
import django.db.models.deletion

from soupui.models import Criticality


class Migration(migrations.Migration):

    dependencies = [
        ("soupui", "0004_service_name"),
    ]

    def add_criticality(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        criticality = apps.get_model("soupui", "Criticality")
        criticality.objects.using(db_alias).bulk_create(
            [
                Criticality(name="Emergency", code="EMERG", index=0),
                Criticality(name="Alert", code="ALERT", index=1),
                Criticality(name="Critical", code="CRIT", index=2),
                Criticality(name="Error", code="ERROR", index=3),
                Criticality(name="Warning", code="WARN", index=4),
                Criticality(name="Notice", code="NOTICE", index=5),
                Criticality(name="Informational", code="INFO", index=6),
                Criticality(name="Debug", code="DEBUG", index=7),
            ]
        )

    def remove_criticality(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        criticality = apps.get_model("soupui", "Criticality")
        criticality.objects.using(db_alias).filter(
            index__in=[0, 1, 2, 3, 4, 5, 6, 7]
        ).delete()

    operations = [
        migrations.CreateModel(
            name="Criticality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("index", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("MIN", "Minimum"),
                            ("EQUAL", "Equal"),
                            ("MAX", "Maximum"),
                        ],
                        default="EQUAL",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "criticality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soupui.criticality",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="threshold",
            field=models.ManyToManyField(to="soupui.threshold"),
        ),
        migrations.RunPython(add_criticality, remove_criticality),
    ]
