# Generated by Django 4.1.1 on 2022-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soupui", "0005_criticality"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criticality",
            options={"ordering": ["index"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="viewed",
            field=models.BooleanField(default=False),
        ),
    ]
